# TODO: Update this to use acme DNS challenge when migrated DNS provider to GoDaddy
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-s2search-prod-tls
spec:
  secretName: wildcard-s2search-prod-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.s2search.co.uk"
  dnsNames:
    - "*.s2search.co.uk"
