apiVersion: v1
kind: Service
metadata:
  name: s2elasticui-loadbalancer
  labels:
    app: s2elasticui
spec:
  type: LoadBalancer
  selector:
    app: s2elasticui
  ports:
    - name: "2999"
      port: 2999
      targetPort: 3000
