parameters:
  - name: deploymentFilesSourceFolder
    type: string
    default: ""
  - name: deploymentFilesTargetFolder
    type: string
    default: ""
  - name: appSettingsSourceFolder
    type: string
    default: ""
  - name: targetRestoreProject
    type: string
    default: ""
  - name: targetWebProject
    type: string
    default: ""
  - name: vstsFeed
    type: string
    default: ""
  - name: buildConfiguration
    type: string
    default: "Release"
  - name: buildVmImage
    type: string
    default: "ubuntu-latest"
  - name: targetTestProject
    type: string
    default: ""
  - name: hasTests
    type: boolean
    default: true
  - name: buildPublishDirectory
    type: string
    default: ""
  - name: containerRegistryConnection
    type: string
    default: ""
  - name: containerRepository
    type: string
    default: ""
  - name: dockerfilePath
    type: string
    default: ""
  - name: dockerBuildContext
    type: string
    default: ""
  - name: dockerBuildTag
    type: string
    default: ""

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "${{ parameters.buildVmImage }}"
        continueOnError: false
        steps:
          - template: steps-copy-deploy-files.yml
            parameters:
              deploymentFilesSourceFolder: "${{ parameters.deploymentFilesSourceFolder }}"
              deploymentFilesTargetFolder: "${{ parameters.deploymentFilesTargetFolder }}"
              appSettingsSourceFolder: "${{ parameters.appSettingsSourceFolder }}"

          - template: steps-build-publish.yml
            parameters:
              targetRestoreProject: "${{ parameters.targetRestoreProject }}"
              targetWebProject: "${{ parameters.targetWebProject }}"
              targetTestProject: "${{ parameters.targetTestProject }}"
              hasTests: "${{ parameters.hasTests }}"
              vstsFeed: "${{ parameters.vstsFeed }}"
              buildConfiguration: "${{ parameters.buildConfiguration }}"
              buildPublishDirectory: "${{ parameters.buildPublishDirectory }}"

          - task: CmdLine@2
            displayName: Docker Build Context Contents
            inputs:
              script: "dir"
              workingDirectory: "${{ parameters.dockerBuildContext }}"

          - template: ../shared/steps-docker-build-push.yml
            parameters:
              containerRegistryConnection: "${{ parameters.containerRegistryConnection }}"
              containerRepository: "${{ parameters.containerRepository }}"
              dockerfilePath: "${{ parameters.dockerfilePath }}"
              dockerBuildContext: "${{ parameters.dockerBuildContext }}"
              dockerBuildTag: "${{ parameters.dockerBuildTag }}"
