parameters:
  - name: targetRestoreProject
    type: string
    default: ""
  - name: targetWebProject
    type: string
    default: ""
  - name: targetTestProject
    type: string
    default: ""
  - name: hasTests
    type: boolean
    default: true
  - name: buildVmImage
    type: string
    default: "ubuntu-latest"
  - name: vstsFeed
    type: string
    default: ""
  - name: buildConfiguration
    type: string
    default: "Release"

stages:
  - stage: BuildValidation
    displayName: Build Validation
    jobs:
      - job: BuildValidation
        displayName: Build Validation
        pool:
          vmImage: "${{ parameters.buildVmImage }}"
        continueOnError: false
        steps:
          - template: steps-build-validation.yml
            parameters:
              targetRestoreProject: "${{ parameters.targetRestoreProject }}"
              targetWebProject: "${{ parameters.targetWebProject }}"
              targetTestProject: "${{ parameters.targetTestProject }}"
              hasTests: ${{ parameters.hasTests }}
              vstsFeed: "${{ parameters.vstsFeed }}"
              buildConfiguration: "${{ parameters.buildConfiguration }}"
