parameters:
  - name: targetRestoreProject
    type: string
    default: ""
  - name: targetWebProject
    type: string
    default: ""
  - name: targetTestProject
    type: string
    default: ""
  - name: hasTests
    type: boolean
    default: true
  - name: vstsFeed
    type: string
    default: ""
  - name: buildConfiguration
    type: string
    default: "Release"

steps:
  - task: DotNetCoreCLI@2
    displayName: Dotnet Restore
    inputs:
      command: "restore"
      projects: "${{ parameters.targetRestoreProject }}"
      feedsToUse: "select"
      vstsFeed: "${{ parameters.vstsFeed }}"

  - task: DotNetCoreCLI@2
    displayName: Dotnet Build
    inputs:
      command: "build"
      projects: "${{ parameters.targetWebProject }}"
      arguments: "-c ${{ parameters.buildConfiguration }}"

  - task: DotNetCoreCLI@2
    displayName: Dotnet Test
    inputs:
      command: "test"
      projects: "${{ parameters.targetTestProject }}"
    condition: and(succeeded(), eq('${{ parameters.hasTests }}', 'true'))
