apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.S2SearchUi.image.name }}-deployment"
  labels:
    app: {{ .Values.S2SearchUi.image.name }}
spec:
  replicas: {{ .Values.S2SearchUi.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.S2SearchUi.image.name }}
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.S2SearchUi.image.name }}
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: {{ .Values.S2SearchUi.image.name }}
          image: {{ .Values.S2SearchUi.image.repository }}:{{ .Values.S2SearchUi.image.tag }}
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: {{ .Values.S2SearchUi.resources.limits.memory }}
              cpu: {{ .Values.S2SearchUi.resources.limits.cpu }}
            requests:
              memory: {{ .Values.S2SearchUi.resources.requests.memory }}
              cpu: {{ .Values.S2SearchUi.resources.requests.cpu }}
          imagePullPolicy: {{ .Values.S2SearchUi.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /vehicletest
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: s2searchui-env
