// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.SFTPGo.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BanStatus
    {
        /// <summary>
        /// Initializes a new instance of the BanStatus class.
        /// </summary>
        public BanStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BanStatus class.
        /// </summary>
        /// <param name="dateTime">if null the host is not banned</param>
        public BanStatus(System.DateTime? dateTime = default(System.DateTime?))
        {
            DateTime = dateTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets if null the host is not banned
        /// </summary>
        [JsonProperty(PropertyName = "date_time")]
        public System.DateTime? DateTime { get; set; }

    }
}
