// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.SFTPGo.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DataProviderStatus
    {
        /// <summary>
        /// Initializes a new instance of the DataProviderStatus class.
        /// </summary>
        public DataProviderStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DataProviderStatus class.
        /// </summary>
        public DataProviderStatus(bool? isActive = default(bool?), string driver = default(string), string error = default(string))
        {
            IsActive = isActive;
            Driver = driver;
            Error = error;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "is_active")]
        public bool? IsActive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "driver")]
        public string Driver { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public string Error { get; set; }

    }
}
