// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.SFTPGo.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FolderQuotaScan
    {
        /// <summary>
        /// Initializes a new instance of the FolderQuotaScan class.
        /// </summary>
        public FolderQuotaScan()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FolderQuotaScan class.
        /// </summary>
        /// <param name="mappedPath">path with an active scan</param>
        /// <param name="startTime">scan start time as unix timestamp in
        /// milliseconds</param>
        public FolderQuotaScan(string mappedPath = default(string), long? startTime = default(long?))
        {
            MappedPath = mappedPath;
            StartTime = startTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets path with an active scan
        /// </summary>
        [JsonProperty(PropertyName = "mapped_path")]
        public string MappedPath { get; set; }

        /// <summary>
        /// Gets or sets scan start time as unix timestamp in milliseconds
        /// </summary>
        [JsonProperty(PropertyName = "start_time")]
        public long? StartTime { get; set; }

    }
}
