// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.SFTPGo.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FTPDBinding
    {
        /// <summary>
        /// Initializes a new instance of the FTPDBinding class.
        /// </summary>
        public FTPDBinding()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FTPDBinding class.
        /// </summary>
        /// <param name="address">TCP address the server listen on</param>
        /// <param name="port">the port used for serving requests</param>
        /// <param name="applyProxyConfig">apply the proxy configuration, if
        /// any</param>
        /// <param name="tlsMode">* `0` - clear or explicit TLS * `1` -
        /// explicit TLS required * `2` - implicit TLS
        /// </param>
        /// <param name="forcePassiveIp">External IP address to expose for
        /// passive connections</param>
        /// <param name="clientAuthType">1 means that client certificate
        /// authentication is required in addition to FTP
        /// authentication</param>
        public FTPDBinding(string address = default(string), int? port = default(int?), bool? applyProxyConfig = default(bool?), int? tlsMode = default(int?), string forcePassiveIp = default(string), int? clientAuthType = default(int?))
        {
            Address = address;
            Port = port;
            ApplyProxyConfig = applyProxyConfig;
            TlsMode = tlsMode;
            ForcePassiveIp = forcePassiveIp;
            ClientAuthType = clientAuthType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets TCP address the server listen on
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public string Address { get; set; }

        /// <summary>
        /// Gets or sets the port used for serving requests
        /// </summary>
        [JsonProperty(PropertyName = "port")]
        public int? Port { get; set; }

        /// <summary>
        /// Gets or sets apply the proxy configuration, if any
        /// </summary>
        [JsonProperty(PropertyName = "apply_proxy_config")]
        public bool? ApplyProxyConfig { get; set; }

        /// <summary>
        /// Gets or sets * `0` - clear or explicit TLS * `1` - explicit TLS
        /// required * `2` - implicit TLS
        ///
        /// </summary>
        [JsonProperty(PropertyName = "tls_mode")]
        public int? TlsMode { get; set; }

        /// <summary>
        /// Gets or sets external IP address to expose for passive connections
        /// </summary>
        [JsonProperty(PropertyName = "force_passive_ip")]
        public string ForcePassiveIp { get; set; }

        /// <summary>
        /// Gets or sets 1 means that client certificate authentication is
        /// required in addition to FTP authentication
        /// </summary>
        [JsonProperty(PropertyName = "client_auth_type")]
        public int? ClientAuthType { get; set; }

    }
}
