// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.SFTPGo.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FTPPassivePortRange
    {
        /// <summary>
        /// Initializes a new instance of the FTPPassivePortRange class.
        /// </summary>
        public FTPPassivePortRange()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FTPPassivePortRange class.
        /// </summary>
        public FTPPassivePortRange(int? start = default(int?), int? end = default(int?))
        {
            Start = start;
            End = end;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "start")]
        public int? Start { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "end")]
        public int? End { get; set; }

    }
}
