// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.SFTPGo.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class FTPServiceStatus
    {
        /// <summary>
        /// Initializes a new instance of the FTPServiceStatus class.
        /// </summary>
        public FTPServiceStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FTPServiceStatus class.
        /// </summary>
        public FTPServiceStatus(bool? isActive = default(bool?), IList<FTPDBinding> bindings = default(IList<FTPDBinding>), FTPPassivePortRange passivePortRange = default(FTPPassivePortRange))
        {
            IsActive = isActive;
            Bindings = bindings;
            PassivePortRange = passivePortRange;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "is_active")]
        public bool? IsActive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bindings")]
        public IList<FTPDBinding> Bindings { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "passive_port_range")]
        public FTPPassivePortRange PassivePortRange { get; set; }

    }
}
