// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.SFTPGo.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ServicesStatusDefender
    {
        /// <summary>
        /// Initializes a new instance of the ServicesStatusDefender class.
        /// </summary>
        public ServicesStatusDefender()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ServicesStatusDefender class.
        /// </summary>
        public ServicesStatusDefender(bool? isActive = default(bool?))
        {
            IsActive = isActive;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "is_active")]
        public bool? IsActive { get; set; }

    }
}
