// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.SFTPGo.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ServicesStatus
    {
        /// <summary>
        /// Initializes a new instance of the ServicesStatus class.
        /// </summary>
        public ServicesStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ServicesStatus class.
        /// </summary>
        public ServicesStatus(SSHServiceStatus ssh = default(SSHServiceStatus), FTPServiceStatus ftp = default(FTPServiceStatus), WebDAVServiceStatus webdav = default(WebDAVServiceStatus), DataProviderStatus dataProvider = default(DataProviderStatus), ServicesStatusDefender defender = default(ServicesStatusDefender))
        {
            Ssh = ssh;
            Ftp = ftp;
            Webdav = webdav;
            DataProvider = dataProvider;
            Defender = defender;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ssh")]
        public SSHServiceStatus Ssh { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ftp")]
        public FTPServiceStatus Ftp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "webdav")]
        public WebDAVServiceStatus Webdav { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "data_provider")]
        public DataProviderStatus DataProvider { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "defender")]
        public ServicesStatusDefender Defender { get; set; }

    }
}
