// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.SFTPGo.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class WebDAVServiceStatus
    {
        /// <summary>
        /// Initializes a new instance of the WebDAVServiceStatus class.
        /// </summary>
        public WebDAVServiceStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WebDAVServiceStatus class.
        /// </summary>
        public WebDAVServiceStatus(bool? isActive = default(bool?), IList<WebDAVBinding> bindings = default(IList<WebDAVBinding>))
        {
            IsActive = isActive;
            Bindings = bindings;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "is_active")]
        public bool? IsActive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bindings")]
        public IList<WebDAVBinding> Bindings { get; set; }

    }
}
