# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
  repositories:
    - repository: DevOpsTemplates
      name: "S2Search/S2Search.Infrastructure"
      type: git

trigger: none

variables:
  - template: DevOps/templates/shared/variables-default.yml@DevOpsTemplates
  - template: DevOps/templates/shared/variables-custom.yml@DevOpsTemplates
    parameters:
      customVariables:
        vmImage: "ubuntu-latest"
        targetRestoreProject: "src/api/**/*.csproj"
        targetWebProject: "src/api/**/ClientConfiguration.csproj"
        targetTestProject: "src/api/**/Tests.csproj"

stages:
  - template: DevOps/templates/dotnet/stage-build-validation.yml@DevOpsTemplates
    parameters:
      targetRestoreProject: "$(targetRestoreProject)"
      targetWebProject: "$(targetWebProject)"
      targetTestProject: "$(targetTestProject)"
      hasTests: true
      buildVmImage: "$(vmImage)"
      vstsFeed: "$(vstsFeed)"
      buildConfiguration: "$(buildConfiguration)"
