# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
  repositories:
    - repository: DevOpsTemplates
      name: "S2Search/S2Search.Infrastructure"
      type: git

trigger: none

variables:
  - template: DevOps/templates/shared/variables-default.yml@DevOpsTemplates
  - template: DevOps/templates/shared/variables-custom.yml@DevOpsTemplates
    parameters:
      customVariables:
        targetRestoreProject: "src/lib/ClientConfigurationApi.Client/*.csproj"
        targetWebProject: "src/lib/ClientConfigurationApi.Client/ClientConfigurationApi.Client.csproj"

stages:
  - template: DevOps/templates/dotnet/stage-build-validation.yml@DevOpsTemplates
    parameters:
      targetRestoreProject: "$(targetRestoreProject)"
      targetWebProject: "$(targetWebProject)"
      hasTests: false
      vstsFeed: "$(vstsFeed)"
      buildConfiguration: "$(buildConfiguration)"
