apiVersion: v1
kind: Service
metadata:
  name: elastic-api-service
  labels:
    app: s2elasticapi
spec:
  type: ClusterIP
  selector:
    app: s2elasticapi
  ports:
    - port: 80
      targetPort: 80
