apiVersion: v1
kind: Service
metadata:
  name: s2adminui-loadbalancer
  labels:
    app: s2adminui
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  selector:
    app: s2adminui
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
    - name: "https"
      port: 443
      targetPort: 3000
    - name: "http"
      port: 80
      targetPort: 3000
