apiVersion: v1
kind: Service
metadata:
  name: s2customerresource-loadbalancer
  labels:
    app: s2customerresourceapi
spec:
  type: LoadBalancer
  selector:
    app: s2customerresourceapi
  ports:
    - name: "6003"
      port: 6003
      targetPort: 80
