name: Docker Build and Push CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  GITLAB_ENDPOINT: registry.gitlab.com
  YOUR_GITLAB_USERNAME: dp-dev0
  YOUR_REPOSITORY: s2search
  IMAGE_NAME: elasticui

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initial Sanity Checks
        run: |
          cd ./
          cd S2Search
          ls -l
          echo $PWD
          echo ${{ env.GITLAB_ENDPOINT }}/${{ env.YOUR_GITLAB_USERNAME }}/${{ env.YOUR_REPOSITORY }}/${{ env.IMAGE_NAME }}
          echo ${{ env.IMAGE_NAME }}:latest ${{ env.GITLAB_ENDPOINT }}/${{ env.YOUR_GITLAB_USERNAME }}/${{ env.YOUR_REPOSITORY }}/${{ env.IMAGE_NAME }}

          echo docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.GITLAB_ENDPOINT }}/${{ env.YOUR_GITLAB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          echo docker login ${{ env.GITLAB_ENDPOINT }}
          echo docker push ${{ env.GITLAB_ENDPOINT }}/${{ env.YOUR_GITLAB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

          echo *******************
          echo ** Variables ******
          echo *******************
          echo GITLAB_ENDPOINT: ${{ env.GITLAB_ENDPOINT }}
          echo YOUR_GITLAB_USERNAME: ${{ env.YOUR_GITLAB_USERNAME }}
          echo YOUR_REPOSITORY: ${{ env.YOUR_REPOSITORY }}
          echo IMAGE_NAME: ${{ env.IMAGE_NAME }}

      - name: Login to GitLab Container Registry
        run: |
          echo ${{ secrets.GITLAB_TOKEN }} | docker login ${{ env.GITLAB_ENDPOINT }} -u ${{ env.YOUR_GITLAB_USERNAME }} --password-stdin

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: "${{ github.workspace }}/S2Search"
          push: false
          tags: ${{ env.IMAGE_NAME }}

      - name: Docker Push Image To GitLab
        run: |
          docker images
          docker tag elasticui:latest registry.gitlab.com/dp-dev0/s2search/elasticui:latest
          docker login registry.gitlab.com
          docker push registry.gitlab.com/dp-dev0/s2search/elasticui:latest
