parameters:
  - name: targetRestoreProject
    type: string
    default: ""
  - name: targetPackageProject
    type: string
    default: ""
  - name: targetTestProject
    type: string
    default: ""
  - name: hasTests
    type: boolean
    default: true
  - name: buildVmImage
    type: string
    default: "ubuntu-latest"
  - name: vstsFeed
    type: string
    default: ""
  - name: buildConfiguration
    type: string
    default: "Release"

stages:
  - stage: NugetPackage
    displayName: Build and Push Package
    jobs:
      - job: NugetPackage
        displayName: Build and Push Package
        pool:
          vmImage: "${{ parameters.buildVmImage }}"
        continueOnError: false
        steps:
          - template: steps-build-validation.yml
            parameters:
              targetRestoreProject: "${{ parameters.targetRestoreProject }}"
              targetWebProject: "${{ parameters.targetPackageProject }}"
              targetTestProject: "${{ parameters.targetTestProject }}"
              hasTests: ${{ parameters.hasTests }}
              vstsFeed: "${{ parameters.vstsFeed }}"
              buildConfiguration: "${{ parameters.buildConfiguration }}"

          - template: steps-nuget-package.yml
            parameters:
              targetPackageProject: "${{ parameters.targetPackageProject }}"
              vstsFeed: "${{ parameters.vstsFeed }}"
