parameters:
  - name: targetRestoreProject
    type: string
    default: ""
  - name: targetWebProject
    type: string
    default: ""
  - name: targetTestProject
    type: string
    default: ""
  - name: hasTests
    type: boolean
    default: true
  - name: vstsFeed
    type: string
    default: ""
  - name: buildConfiguration
    type: string
    default: "Release"
  - name: buildPublishDirectory
    type: string
    default: ""

steps:
  - template: steps-build-validation.yml
    parameters:
      targetRestoreProject: "${{ parameters.targetRestoreProject }}"
      targetWebProject: "${{ parameters.targetWebProject }}"
      targetTestProject: "${{ parameters.targetTestProject }}"
      hasTests: "${{ parameters.hasTests }}"
      vstsFeed: "${{ parameters.vstsFeed }}"
      buildConfiguration: "${{ parameters.buildConfiguration }}"

  - task: DotNetCoreCLI@2
    displayName: Dotnet Publish
    inputs:
      command: "publish"
      publishWebProjects: true
      arguments: "--output ${{ parameters.buildPublishDirectory }} -c ${{ parameters.buildConfiguration }}"
      zipAfterPublish: false

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
      PathtoPublish: "${{ parameters.buildPublishDirectory }}"
      ArtifactName: "drop"
      publishLocation: "Container"
