/*
Deployment script for S2_Search

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

-- =============================
-- Drop Table Definitions
-- =============================

DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS FeedCredentials;
DROP TABLE IF EXISTS FeedCurrentDocuments;
DROP TABLE IF EXISTS Feeds;
DROP TABLE IF EXISTS SearchConfiguration;
DROP TABLE IF EXISTS SearchIndex;
DROP TABLE IF EXISTS SearchIndexRequestLog;
DROP TABLE IF EXISTS SearchInsightsData;
DROP TABLE IF EXISTS SearchInstanceKeys;
DROP TABLE IF EXISTS SearchInstances;
DROP TABLE IF EXISTS Synonyms;
DROP TABLE IF EXISTS Themes;

-- =============================
-- Table Definitions
-- =============================

CREATE TABLE Customers (
    Id               UUID           NOT NULL,
    BusinessName     TEXT           NULL,
    CustomerEndpoint TEXT           NULL,
    CreatedDate      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ModifiedDate     TIMESTAMP      NULL,
    CONSTRAINT PK_Users PRIMARY KEY (Id)
);

CREATE TABLE FeedCredentials (
    Id               UUID           NOT NULL,
    SearchIndexId    UUID           NOT NULL,
    Username         TEXT           NOT NULL,
    PasswordHash     TEXT           NOT NULL,
    CreatedDate      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ModifiedDate     TIMESTAMP      NULL
);

CREATE TABLE FeedCurrentDocuments (
    Id               TEXT           NOT NULL,
    SearchIndexId    UUID           NOT NULL,
    CreatedDate      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Feeds (
    Id               UUID           NOT NULL,
    FeedType         TEXT           NOT NULL,
    FeedScheduleCron TEXT           NOT NULL,
    SearchIndexId    UUID           NOT NULL,
    DataFormat       TEXT           NOT NULL,
    CreatedDate      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SupersededDate   TIMESTAMP      NULL,
    IsLatest         BOOLEAN        NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_Feeds PRIMARY KEY (Id)
);

CREATE TABLE SearchConfiguration (
    Id               UUID           NOT NULL,
    Value            TEXT           NOT NULL,
    SearchIndexId    UUID           NOT NULL,
    Key              TEXT           NOT NULL,
    FriendlyName     TEXT           NOT NULL,
    Description      TEXT           NOT NULL,
    DataType         TEXT           NOT NULL,
    OrderIndex       INT            NULL,
    CreatedDate      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ModifiedDate     TIMESTAMP      NULL,
    CONSTRAINT PK_SearchConfigurationMappingsCombined PRIMARY KEY (Id)
);

CREATE TABLE SearchIndex (
    Id               UUID           NOT NULL,
    CustomerId       UUID           NOT NULL,
    SearchInstanceId UUID           NULL,
    IndexName        TEXT           NOT NULL,
    FriendlyName     TEXT           NOT NULL,
    PricingSkuId     TEXT           NOT NULL,
    CreatedDate      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_SearchIndex PRIMARY KEY (Id)
);

CREATE TABLE SearchIndexRequestLog (
    Id               UUID           NOT NULL,
    SearchIndexId    UUID           NOT NULL,
    Count            INT            NOT NULL DEFAULT 0,
    Date             TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CreatedDate      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ModifiedDate     TIMESTAMP      NOT NULL,
    CONSTRAINT PK_SearchIndexRequestLog PRIMARY KEY (Id)
);

CREATE TABLE SearchInsightsData (
    Id               UUID           NOT NULL,
    SearchIndexId    UUID           NOT NULL,
    DataCatery       TEXT           NOT NULL,
    DataPoint        TEXT           NOT NULL,
    Count            INT            NOT NULL DEFAULT 0,
    Date             TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CreatedDate      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ModifiedDate     TIMESTAMP      NOT NULL,
    CONSTRAINT PK_SearchInsightsData PRIMARY KEY (Id)
);

CREATE TABLE SearchInstanceKeys (
    Id               UUID           NOT NULL,
    SearchInstanceId UUID           NOT NULL,
    KeyType          TEXT           NOT NULL,
    Name             TEXT           NOT NULL,
    ApiKey           TEXT           NOT NULL,
    CreatedDate      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ModifiedDate     TIMESTAMP      NULL,
    IsLatest         BOOLEAN        NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_SearchInstanceKeys PRIMARY KEY (Id)
);

CREATE TABLE SearchInstances (
    Id               UUID           NOT NULL,
    CustomerId       UUID           NOT NULL,
    ServiceName      TEXT           NOT NULL,
    Location         TEXT           NOT NULL,
    PricingTier      TEXT           NOT NULL,
    Replicas         INT            NULL,
    Partitions       INT            NULL,
    IsShared         BOOLEAN        NOT NULL,
    Type             TEXT           NOT NULL,
    RootEndpoint     TEXT           NULL,
    CONSTRAINT PK_SearchInstances PRIMARY KEY (Id)
);

CREATE TABLE Synonyms (
    Id               UUID           NOT NULL,
    Catery           TEXT           NULL,
    SearchIndexId    UUID           NULL,
    KeyWord          TEXT           NULL,
    SolrFormat       TEXT           NOT NULL,
    CreatedDate      TIMESTAMP      NOT NULL,
    SupersededDate   TIMESTAMP      NULL,
    IsLatest         BOOLEAN        NOT NULL,
    CONSTRAINT PK_CombinedSynonyms PRIMARY KEY (Id)
);

CREATE TABLE Themes (
    Id                 UUID         NOT NULL,
    PrimaryHexColour   TEXT         NULL,
    SecondaryHexColour TEXT         NULL,
    NavBarHexColour    TEXT         NULL,
    LoURL              TEXT         NULL,
    MissingImageURL    TEXT         NULL,
    CustomerId         UUID         NULL,
    SearchIndexId      UUID         NULL,
    CreatedDate        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ModifiedDate       TIMESTAMP    NULL,
    CONSTRAINT PK_Themes PRIMARY KEY (Id)
);