# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
  repositories:
    - repository: DevOpsTemplates
      name: "S2Search/S2Search.Infrastructure"
      type: git

trigger: none 

variables:
  - template: DevOps/templates/shared/variables-default.yml@DevOpsTemplates
    parameters:
      dockerBuildContext: "$(Build.ArtifactStagingDirectory)/Search"
      containerRepository: "$(containerNamespace)/s2search/searchapi"
  - template: DevOps/templates/shared/variables-custom.yml@DevOpsTemplates
    parameters:
      customVariables:
        vmImage: "ubuntu-latest"
        targetRestoreProject: "**/*.csproj"
        targetWebProject: "**/Search.csproj"
        targetTestProject: "**/Tests.csproj"

stages:
  - template: DevOps/templates/dotnet/stage-build-validation.yml@DevOpsTemplates
    parameters:
      dotnetVersion: "7.x"
      targetRestoreProject: "${{ variables.targetRestoreProject }}"
      targetWebProject: "${{ variables.targetWebProject }}"
      targetTestProject: "${{ variables.targetTestProject }}"
      hasTests: true
      buildVmImage: "${{ variables.vmImage }}"
      vstsFeed: "${{ variables.vstsFeed }}"
      buildConfiguration: "${{ variables.buildConfiguration }}"
