apiVersion: v1
kind: Service
metadata:
  name: s2searchui-loadbalancer
  labels:
    app: s2searchui
spec:
  type: LoadBalancer
  selector:
    app: s2searchui
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
