parameters:
  - name: scriptList
    type: stepList
    default: {}

stages:
  - stage: VariableValues
    jobs:
      - job:
        displayName: "Output Variables"
        steps: ${{ parameters.scriptList }}
