parameters:
  - name: deployVmImage
    type: string
    default: "ubuntu-latest"
  - name: deployEnvironment
    type: string
    default: ""
  - name: azureSubscription
    type: string
    default: ""
  - name: azureResourceGroup
    type: string
    default: ""
  - name: appServiceName
    type: string
    default: ""
  - name: fullContainerImageUrl
    type: string
    default: ""
  - name: containerRegistryUrl
    type: string
    default: ""
  - name: containerRegistryUsername
    type: string
    default: ""
  - name: containerRegistryPassword
    type: string
    default: ""
  - name: workingDirectory
    type: string
    default: ""
  - name: deployScriptsPath
    type: string
    default: ""
  - name: "secrets"
    type: object
    default: {}
  - name: templatesRepositoryName
    type: string
    default: ""

stages:
  - stage: DeployAppService
    displayName: Deploy to App Service
    jobs:
      - deployment: DeployWebAppToAppService
        displayName: Deploy Web App
        pool:
          vmImage: "${{ parameters.deployVmImage }}"
        # Creates an environment if it doesn't exist.
        environment: "${{ parameters.deployEnvironment }}"
        strategy:
          # Default deployment strategy
          runOnce:
            deploy:
              steps:
                - template: steps-validate-vars.yml
                  parameters:
                    workingDirectory: "${{ parameters.workingDirectory }}"
                    deployScriptsPath: "${{ parameters.deployScriptsPath }}"
                    secrets: "${{ parameters.secrets }}"
                    templatesRepositoryName: "${{ parameters.templatesRepositoryName }}"

                - template: steps-deploy-app-service-container.yml
                  parameters:
                    azureSubscription: "${{ parameters.azureSubscription }}"
                    azureResourceGroup: "${{ parameters.azureResourceGroup }}"
                    appServiceName: "${{ parameters.appServiceName }}"
                    fullContainerImageUrl: "${{ parameters.fullContainerImageUrl }}"
                    containerRegistryUrl: "${{ parameters.containerRegistryUrl }}"
                    containerRegistryUsername: "${{ parameters.containerRegistryUsername }}"
                    containerRegistryPassword: "${{ parameters.containerRegistryPassword }}"
