parameters:
  - name: containerRegistryConnection
    type: string
    default: ""
  - name: containerRepository
    type: string
    default: ""
  - name: dockerfilePath
    type: string
    default: ""
  - name: dockerBuildContext
    type: string
    default: ""
  - name: dockerBuildTag
    type: string
    default: ""

steps:
  - task: Docker@2
    displayName: Build docker image
    inputs:
      containerRegistry: "${{ parameters.containerRegistryConnection }}"
      repository: "${{ parameters.containerRepository }}"
      command: "build"
      Dockerfile: "${{ parameters.dockerfilePath }}"
      buildContext: "${{ parameters.dockerBuildContext }}"
      tags: |
        ${{ parameters.dockerBuildTag }}
        latest
      addPipelineData: false
      addBaseImageData: false

  - task: Docker@2
    displayName: Push docker image
    inputs:
      containerRegistry: "${{ parameters.containerRegistryConnection }}"
      repository: "${{ parameters.containerRepository }}"
      command: "push"
      tags: |
        ${{ parameters.dockerBuildTag }}
        latest
      addPipelineData: false
      addBaseImageData: false
