apiVersion: apps/v1
kind: Deployment
metadata:
  name: $env:SERVICENAME-deployment
  labels:
    app: $env:SERVICENAME
spec:
  replicas: $env:REPLICAS
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: $env:SERVICENAME
  template:
    metadata:
      labels:
        app: $env:SERVICENAME
    spec:
      containers:
        - name: $env:SERVICENAME-container
          image: $env:CONTAINERIMAGEURL
          env:
            - name: NODE_ENV
              value: $env:NODE_ENV
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          livenessProbe:
            httpGet:
              path: /api/probe/live
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/probe/ready
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
#            limits:
#              cpu: 100m
#              memory: 200Mi