apiVersion: v1
kind: Service
metadata:
  name: s2clientconfigurationapi-nodeport
  labels:
    app: s2clientconfigurationapi
spec:
  type: NodePort
  selector:
    app: s2clientconfigurationapi
  ports:
    - port: 80
      targetPort: 80
