apiVersion: v1
kind: Service
metadata:
  name: s2clientconfigurationapi-loadbalancer
  labels:
    app: s2clientconfigurationapi
spec:
  type: LoadBalancer
  selector:
    app: s2clientconfigurationapi
  ports:
    - name: "6002"
      port: 6002
      targetPort: 80
