// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.SFTPGo.Client.AutoRest
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Change.
    /// </summary>
    public static partial class ChangeExtensions
    {
            /// <summary>
            /// Change the password for the logged in admin
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// </param>
            public static ApiResponse Password(this IChange operations, PwdChange body)
            {
                return operations.PasswordAsync(body).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Change the password for the logged in admin
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='body'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ApiResponse> PasswordAsync(this IChange operations, PwdChange body, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PasswordWithHttpMessagesAsync(body, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
