// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.SFTPGo.Client.AutoRest
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Close.
    /// </summary>
    public static partial class CloseExtensions
    {
            /// <summary>
            /// Terminate an active connection
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='connectionID'>
            /// ID of the connection to close
            /// </param>
            public static ApiResponse Connection(this IClose operations, string connectionID)
            {
                return operations.ConnectionAsync(connectionID).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Terminate an active connection
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='connectionID'>
            /// ID of the connection to close
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ApiResponse> ConnectionAsync(this IClose operations, string connectionID, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ConnectionWithHttpMessagesAsync(connectionID, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
