apiVersion: v1
kind: Service
metadata:
  name: s2elasticapi-nodeport
  labels:
    app: s2elasticapi
spec:
  type: NodePort
  selector:
    app: s2elasticapi
  ports:
    - port: 80
      targetPort: 80
