{
  "openapi": "3.0.1",
  "info": {
    "title": "Client Configuration API",
    "version": "v1.0.0"
  },
  "paths": {
    "/api/Configuration/queryCredentials/{customerEndpoint}": {
      "get": {
        "tags": [
          "Configuration"
        ],
        "summary": "Retrieve search index query credentials by the requested customerEndpoint",
        "operationId": "GetSearchIndexQueryCredentials",
        "parameters": [
          {
            "name": "customerEndpoint",
            "in": "path",
            "description": "The host that is calling the application consuming this endpoint.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/SearchIndexQueryCredentials"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SearchIndexQueryCredentials"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/SearchIndexQueryCredentials"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "500": {
            "description": "Server Error"
          }
        }
      }
    },
    "/api/Configuration/theme/{customerEndpoint}": {
      "get": {
        "tags": [
          "Configuration"
        ],
        "summary": "Retrieve the theme for the requested customerEndpoint",
        "operationId": "GetTheme",
        "parameters": [
          {
            "name": "customerEndpoint",
            "in": "path",
            "description": "The host that is calling the application consuming this endpoint.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/Theme"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Theme"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/Theme"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "500": {
            "description": "Server Error"
          }
        }
      }
    },
    "/api/Configuration/search/{customerEndpoint}": {
      "get": {
        "tags": [
          "Configuration"
        ],
        "summary": "Retrieve the configuration for a search index",
        "operationId": "GetSearchConfiguration",
        "parameters": [
          {
            "name": "customerEndpoint",
            "in": "path",
            "description": "The host that is calling the application consuming this endpoint.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/SearchConfigurationOption"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/SearchConfigurationOption"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/SearchConfigurationOption"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "500": {
            "description": "Server Error"
          }
        }
      }
    },
    "/api/Configuration/search/GenericSynonyms/{category}": {
      "get": {
        "tags": [
          "Configuration"
        ],
        "summary": "Retrieve the Generic Synonyms",
        "operationId": "GetGenericSynonyms",
        "parameters": [
          {
            "name": "category",
            "in": "path",
            "description": "The category of the generic synonyms to retrieve.",
            "required": true,
            "schema": {
              "type": "string",
              "default": "vehicles"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/GenericSynonyms"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/GenericSynonyms"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/GenericSynonyms"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "500": {
            "description": "Server Error"
          }
        }
      }
    },
    "/api/Status": {
      "get": {
        "tags": [
          "Status"
        ],
        "operationId": "GetAPIStatus",
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "GenericSynonyms": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "category": {
            "type": "string",
            "nullable": true
          },
          "solrFormat": {
            "type": "string",
            "nullable": true
          },
          "createdDate": {
            "type": "string",
            "format": "date-time"
          }
        },
        "additionalProperties": false
      },
      "ProblemDetails": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "nullable": true
          },
          "title": {
            "type": "string",
            "nullable": true
          },
          "status": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "detail": {
            "type": "string",
            "nullable": true
          },
          "instance": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": { }
      },
      "SearchConfigurationOption": {
        "type": "object",
        "properties": {
          "seachConfigurationOptionId": {
            "type": "string",
            "format": "uuid"
          },
          "key": {
            "type": "string",
            "nullable": true
          },
          "value": {
            "type": "string",
            "nullable": true
          },
          "friendlyName": {
            "type": "string",
            "nullable": true
          },
          "description": {
            "type": "string",
            "nullable": true
          },
          "dataType": {
            "type": "string",
            "nullable": true
          },
          "createdDate": {
            "type": "string",
            "format": "date-time"
          },
          "modifiedDate": {
            "type": "string",
            "format": "date-time"
          }
        },
        "additionalProperties": false
      },
      "SearchIndexQueryCredentials": {
        "type": "object",
        "properties": {
          "searchIndexId": {
            "type": "string",
            "format": "uuid"
          },
          "queryApiKey": {
            "type": "string",
            "nullable": true
          },
          "searchIndexName": {
            "type": "string",
            "nullable": true
          },
          "searchInstanceName": {
            "type": "string",
            "nullable": true
          },
          "searchInstanceEndpoint": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "Theme": {
        "type": "object",
        "properties": {
          "themeId": {
            "type": "string",
            "format": "uuid"
          },
          "primaryHexColour": {
            "type": "string",
            "nullable": true
          },
          "secondaryHexColour": {
            "type": "string",
            "nullable": true
          },
          "navBarHexColour": {
            "type": "string",
            "nullable": true
          },
          "logoURL": {
            "type": "string",
            "nullable": true
          },
          "missingImageURL": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    }
  }
}