// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.CustomerResourceApi.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CustomerPricingTier
    {
        /// <summary>
        /// Initializes a new instance of the CustomerPricingTier class.
        /// </summary>
        public CustomerPricingTier()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CustomerPricingTier class.
        /// </summary>
        public CustomerPricingTier(string skuId = default(string), string name = default(string), string description = default(string), double? price = default(double?))
        {
            SkuId = skuId;
            Name = name;
            Description = description;
            Price = price;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "skuId")]
        public string SkuId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "price")]
        public double? Price { get; set; }

    }
}
