// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.CustomerResourceApi.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SearchIndexKeyDeletionRequest
    {
        /// <summary>
        /// Initializes a new instance of the SearchIndexKeyDeletionRequest
        /// class.
        /// </summary>
        public SearchIndexKeyDeletionRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SearchIndexKeyDeletionRequest
        /// class.
        /// </summary>
        public SearchIndexKeyDeletionRequest(System.Guid? searchIndexId = default(System.Guid?), System.Guid? customerId = default(System.Guid?), IList<QueryKey> keysToDelete = default(IList<QueryKey>))
        {
            SearchIndexId = searchIndexId;
            CustomerId = customerId;
            KeysToDelete = keysToDelete;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "searchIndexId")]
        public System.Guid? SearchIndexId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerId")]
        public System.Guid? CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "keysToDelete")]
        public IList<QueryKey> KeysToDelete { get; set; }

    }
}
