// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.CustomerResourceApi.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SearchInterface
    {
        /// <summary>
        /// Initializes a new instance of the SearchInterface class.
        /// </summary>
        public SearchInterface()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SearchInterface class.
        /// </summary>
        public SearchInterface(int? searchInterfaceId = default(int?), string searchEndpoint = default(string), int? type = default(int?), string logoURL = default(string), string bannerStyle = default(string))
        {
            SearchInterfaceId = searchInterfaceId;
            SearchEndpoint = searchEndpoint;
            Type = type;
            LogoURL = logoURL;
            BannerStyle = bannerStyle;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "searchInterfaceId")]
        public int? SearchInterfaceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "searchEndpoint")]
        public string SearchEndpoint { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public int? Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "logoURL")]
        public string LogoURL { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bannerStyle")]
        public string BannerStyle { get; set; }

    }
}
