// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.CustomerResourceApi.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SearchIndex
    {
        /// <summary>
        /// Initializes a new instance of the SearchIndex class.
        /// </summary>
        public SearchIndex()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SearchIndex class.
        /// </summary>
        public SearchIndex(System.Guid? searchIndexId = default(System.Guid?), System.Guid? searchInstanceId = default(System.Guid?), System.Guid? customerId = default(System.Guid?), string friendlyName = default(string), string indexName = default(string), string indexType = default(string))
        {
            SearchIndexId = searchIndexId;
            SearchInstanceId = searchInstanceId;
            CustomerId = customerId;
            FriendlyName = friendlyName;
            IndexName = indexName;
            IndexType = indexType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "searchIndexId")]
        public System.Guid? SearchIndexId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "searchInstanceId")]
        public System.Guid? SearchInstanceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerId")]
        public System.Guid? CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "friendlyName")]
        public string FriendlyName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "indexName")]
        public string IndexName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "indexType")]
        public string IndexType { get; set; }

    }
}
