// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.CustomerResourceApi.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Theme
    {
        /// <summary>
        /// Initializes a new instance of the Theme class.
        /// </summary>
        public Theme()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Theme class.
        /// </summary>
        public Theme(System.Guid? themeId = default(System.Guid?), string primaryHexColour = default(string), string secondaryHexColour = default(string), string navBarHexColour = default(string), string logoURL = default(string), System.Guid? customerId = default(System.Guid?), System.Guid? searchIndexId = default(System.Guid?), System.DateTime? createdDate = default(System.DateTime?), System.DateTime? modifiedDate = default(System.DateTime?))
        {
            ThemeId = themeId;
            PrimaryHexColour = primaryHexColour;
            SecondaryHexColour = secondaryHexColour;
            NavBarHexColour = navBarHexColour;
            LogoURL = logoURL;
            CustomerId = customerId;
            SearchIndexId = searchIndexId;
            CreatedDate = createdDate;
            ModifiedDate = modifiedDate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "themeId")]
        public System.Guid? ThemeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "primaryHexColour")]
        public string PrimaryHexColour { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "secondaryHexColour")]
        public string SecondaryHexColour { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "navBarHexColour")]
        public string NavBarHexColour { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "logoURL")]
        public string LogoURL { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerId")]
        public System.Guid? CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "searchIndexId")]
        public System.Guid? SearchIndexId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdDate")]
        public System.DateTime? CreatedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modifiedDate")]
        public System.DateTime? ModifiedDate { get; set; }

    }
}
