// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.CustomerResourceApi.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ThemeCollection
    {
        /// <summary>
        /// Initializes a new instance of the ThemeCollection class.
        /// </summary>
        public ThemeCollection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ThemeCollection class.
        /// </summary>
        public ThemeCollection(IList<Theme> themes = default(IList<Theme>))
        {
            Themes = themes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "themes")]
        public IList<Theme> Themes { get; set; }

    }
}
