// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.ClientConfigurationApi.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SearchIndexQueryCredentials
    {
        /// <summary>
        /// Initializes a new instance of the SearchIndexQueryCredentials
        /// class.
        /// </summary>
        public SearchIndexQueryCredentials()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SearchIndexQueryCredentials
        /// class.
        /// </summary>
        public SearchIndexQueryCredentials(System.Guid? searchIndexId = default(System.Guid?), string queryApiKey = default(string), string searchIndexName = default(string), string searchInstanceName = default(string), string searchInstanceEndpoint = default(string))
        {
            SearchIndexId = searchIndexId;
            QueryApiKey = queryApiKey;
            SearchIndexName = searchIndexName;
            SearchInstanceName = searchInstanceName;
            SearchInstanceEndpoint = searchInstanceEndpoint;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "searchIndexId")]
        public System.Guid? SearchIndexId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "queryApiKey")]
        public string QueryApiKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "searchIndexName")]
        public string SearchIndexName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "searchInstanceName")]
        public string SearchInstanceName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "searchInstanceEndpoint")]
        public string SearchInstanceEndpoint { get; set; }

    }
}
