# ClusterIP Service for the Next.js UI Application
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.S2SearchUi.image.name }}-service"
  namespace: s2search
spec:
  # ClusterIP makes this Service only accessible internally within the cluster,
  # which is necessary for the Ingress to target it.
  type: ClusterIP
  selector:
    # This must match the label on your UI Deployment Pods
    app: s2search-ui-service
  ports:
    - name: http
      protocol: TCP
      # The port the service exposes internally
      port: 3000
      # The targetPort is the port the Next.js container listens on (from the logs)
      targetPort: 3000
