apiVersion: v1
kind: Service
metadata:
  name: kibana-loadbalancer
  labels:
    app: kibana
spec:
  type: LoadBalancer
  selector:
    app: kibana
  ports:
    - name: "5601"
      port: 5601
      targetPort: 5601
