apiVersion: v1
kind: Service
metadata:
  name: s2searchapi-loadbalancer
  labels:
    app: s2searchapi
spec:
  type: LoadBalancer
  selector:
    app: s2searchapi
  ports:
    - name: "6001"
      port: 6001
      targetPort: 80
