apiVersion: v1
kind: Service
metadata:
  name: s2searchapi-nodeport
  labels:
    app: s2searchapi
spec:
  type: NodePort
  selector:
    app: s2searchapi
  ports:
    - port: 80
      targetPort: 80
