apiVersion: v1
kind: ConfigMap
metadata:
  name: searchapi-appsettings-production
data:
  appsettings.json: |-
    {
      "ApplicationInsights": {
        "InstrumentationKey": "5870ccb6-9d43-45e0-b10b-aad1b89df151"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        },
        "ApplicationInsights": {
          "LogLevel": {
            "Default": "Information",
            "Microsoft": "Warning",
            "Microsoft.Hosting.Lifetime": "Information"
          }
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "StorageQueue": "DefaultEndpointsProtocol=https;AccountName=storageaccountrgfuna06f;AccountKey=5hSaXVLFnckpbGVtY/MLb5BTQPGgUEn6ETukrJJ8+kjrguxytkFY621Pe8UQUpYx71enk2ZdoTg/o8mJX2i3vA==;EndpointSuffix=core.windows.net"
      },
      "AppSettings": {
        "DemoSearchCredentials": {
          "UseDemoSearchCredentials": false,
          "SearchCredentialsQueryKey": "03F111875473D3CE6F5B70C1333EDC96",
          "SearchCredentialsIndexId": "6FB3C6D1-F480-47B5-9934-02E611AEFD02",
          "SearchCredentialsIndexName": "marshall-cars-vehicles",
          "SearchCredentialsInstanceEndpoint": "https://demo-dev-jg-uks-1.search.windows.net",
          "SearchCredentialsInstanceName": "demo-dev-jg-uks-1"
        },
        "SearchSettings": {
          "UseRequestedCallingHost": true,
          "DefaultSearchOrderBy": "price desc",
          "FacetOrder": "[\"make\", \"model\", \"variant\", \"price\", \"monthlyPrice\", \"location\", \"year\", \"mileage\", \"transmission\", \"fuelType\", \"bodyStyle\", \"engineSize\", \"doors\", \"colour\"]",
          "DefaultFacetsURL": "https://onedrive.live.com/download?cid=7B0A3FF24BCC6D53&resid=7B0A3FF24BCC6D53%21111031&authkey=AKa46c29qaNeNfE",
          "FacetNamesToMatch": "[\"make\", \"model\", \"transmission\", \"fuelType\", \"year\", \"colour\", \"bodyStyle\" ]",
          "FacetEdgeCases": "[{\"SearchTerm\": \"6\", \"FullSearchTerm\": \"bmw\", \"Result\":true}, {\"SearchTerm\": \"6\", \"FullSearchTerm\": \"mazda\", \"Result\":false}, {\"SearchTerm\": \"6\", \"FullSearchTerm\": \"6 door\", \"Result\":true}, {\"SearchTerm\": \"6\", \"FullSearchTerm\": \"6 doors\", \"Result\":true}]",
          "FacetCurrencyRanges": "price,monthlyPrice",
          "FacetNonCurrencyRange": "mileage",
          "FacetMaxRangeToValue": 20000000,
          "FacetToOverrideDisplay": "engineSize,mileage,doors"
        },
        "FacetSettings": {
          "Make": "make, count:9999",
          "Model": "model, count:9999",
          "Variant": "variant, count:9999",
          "Location": "location, count:9999",
          "Price": "price, values:5001|10001|20001|30001|40001|50001|60001|70001|80001|90001|100001|150001|200001|500001|1000001",
          "MonthlyPrice": "monthlyPrice, values:201|401|601|801|1001|1501|2001",
          "Mileage": "mileage, values:1000|5000|10000|20000|30000|50000|75000|100000",
          "FuelType": "fuelType, count:9999",
          "Transmission": "transmission, count:9999",
          "Doors": "doors, count:9999",
          "EngineSize": "engineSize, count:9999",
          "BodyStyle": "bodyStyle, count:9999",
          "Colour": "colour, count:9999",
          "Year": "year, count:9999"
        },
        "ClientConfigurationSettings": {
          "ClientConfigurationEndpoint": "http://adminapi-api-service",
          "HeaderAPISubscriptionName": "Ocp-Apim-Subscription-Key",
          "APISubscriptionKey": "bc2f460930b049bfb7554e06d280a2c0"          
        },
        "MemoryCacheSettings": {
          "SearchCacheSlidingExpirySeconds": 1,
          "ConfigCacheSlidingExpirySeconds": 1,
          "DefaultFacetsCacheExpiryInSeconds": 60,
          "GenericSynonymsCacheExpiryInSeconds": 86400
        },
        "RedisCacheSettings": {
          "RedisConnectionString": "redis-0.redis.redis.svc.cluster.local,ssl=false,password=a-very-complex-password-here,abortConnect=false,connectTimeout=15000,responseTimeout=5000",
          "DefaultCacheExpiryInSeconds": 3600
        },
        "AdminSettings": {
          "AdminEndpoint": "http://adminapi-api-service/"
        }
      }
    }
