parameters:
  - name: workingDirectory
    type: string
    default: ""
  - name: deployVmImage
    type: string
    default: "ubuntu-latest"
  - name: deployEnvironment
    type: string
    default: ""
  - name: deployScriptsPath
    type: string
    default: ""
  - name: kubernetesServiceConnection
    type: string
    default: ""
  - name: kubernetesNamespace
    type: string
    default: ""
  - name: "secrets"
    type: object
    default: {}
  - name: templatesRepositoryName
    type: string
    default: ""
  - name: azureSubscription
    type: string
    default: ""
  - name: appName
    type: string
    default: ""
  - name: containerImageUrl
    type: string
    default: ""
  - name: deployType
    type: string
    default: ""

stages:
  - ${{ if eq(parameters.deployType, 'Kubernetes') }}:
      - template: stage-deploy-k8s.yml
        parameters:
          workingDirectory: "${{ parameters.workingDirectory }}"
          deployVmImage: "${{ parameters.deployVmImage }}"
          deployEnvironment: "${{ parameters.deployEnvironment }}"
          deployScriptsPath: "${{ parameters.deployScriptsPath }}"
          kubernetesServiceConnection: "${{ parameters.kubernetesServiceConnection }}"
          kubernetesNamespace: "${{ parameters.kubernetesNamespace }}"
          templatesRepositoryName: "${{ parameters.templatesRepositoryName }}"
          secrets: "${{ parameters.secrets }}"

  - ${{ if eq(parameters.deployType, 'AppService') }}:
      - template: stage-deploy-app-service-container.yml
        parameters:
          deployVmImage: "${{ parameters.deployVmImage }}"
          deployEnvironment: "${{ parameters.deployEnvironment }}"
          azureSubscription: "${{ parameters.azureSubscription }}"
          appName: "${{ parameters.appName }}"
          containerImageUrl: "${{ parameters.containerImageUrl }}"
