apiVersion: v1
kind: Service
metadata:
  name: clientconfiguration-api-service
  labels:
    app: s2clientconfigurationapi
spec:
  type: ClusterIP
  selector:
    app: s2clientconfigurationapi
  ports:
    - port: 80
      targetPort: 80
