apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-loadbalancer
  labels:
    app: elasticsearch
spec:
  type: LoadBalancer
  selector:
    app: elasticsearch
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
