apiVersion: v1
kind: Service
metadata:
  name: mysql-ftp-service
  labels:
    app: mysql-ftp
    tier: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-ftp
    tier: mysql
  clusterIP: None