# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

variables:
  uiBuild: "build"
  tag: "$(Build.BuildId)"
  vmImageName: "ubuntu-latest"
  nodeVersion: "14.x"
  archiveType: "zip"
pool:
  vmImage: $(vmImageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "$(nodeVersion)"
    displayName: "Install Node.js"

  - script: |
      npm install
      npm run build:production
    displayName: "npm install and build"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(uiBuild)"
      includeRootFolder: true
      archiveType: "$(archiveType)"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(tag).$(archiveType)"
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)"
      artifactName: drop
