export const SET_SELECTEDSEARCHINDEXID_SUCCESS =
  "SET_SELECTEDSEARCHINDEXID_SUCCESS";
export const LOAD_CUSTOMERDETAILS_SUCCESS = "LOAD_CUSTOMERDETAILS_SUCCESS";
export const LOAD_SEARCHINDEXES_SUCCESS = "LOAD_SEARCHINDEXES_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
