apiVersion: v1
kind: ConfigMap
metadata:
  name: s2elasticapi-appsettings-production
data:
  appsettings.json: |-
    {
      "ApplicationInsights": {
        "InstrumentationKey": "b8e5f8e9-1604-48fd-9d4e-0bc55837d106"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Error",
          "Microsoft": "Error",
          "Microsoft.Hosting.Lifetime": "Error"
        },
        "ApplicationInsights": {
          "LogLevel": {
            "Default": "Error",
            "Microsoft": "Error",
            "Microsoft.Hosting.Lifetime": "Error"
          }
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "StorageQueue": "DefaultEndpointsProtocol=https;AccountName=s2storagedev;AccountKey=3qMRIgisGsfc5AV/x5wDKYVbSEfw+lPropDKBy67+fG32BS+WHL7a2zyH/A/p2bJKEDCH5w+EGJP+AStqFdPsA==;EndpointSuffix=core.windows.net"
      },
      "AppSettings": {
        "ElasticSearchSettings": {
          "Endpoint": "http://elasticsearch:9200",
          "Username": "",
          "Password": "",
          "InvokeWithClientCertificate": false
        },
        "SearchSettings": {
          "UseRequestedCallingHost": true,
          "DefaultSearchOrderBy": "price desc",
          "FacetOrder": "[\"make\", \"model\", \"variant\", \"price\", \"monthlyPrice\", \"location\", \"year\", \"mileage\", \"transmission\", \"fuelType\", \"bodyStyle\", \"engineSize\", \"doors\", \"colour\"]",
          "DefaultFacetsURL": "https://onedrive.live.com/download?cid=7B0A3FF24BCC6D53&resid=7B0A3FF24BCC6D53%21111031&authkey=AKa46c29qaNeNfE",
          "FacetNamesToMatch": "[\"make\", \"model\", \"transmission\", \"fuelType\", \"year\", \"colour\", \"bodyStyle\" ]",
          "FacetEdgeCases": "[{\"SearchTerm\": \"6\", \"FullSearchTerm\": \"bmw\", \"Result\":true}, {\"SearchTerm\": \"6\", \"FullSearchTerm\": \"mazda\", \"Result\":false}, {\"SearchTerm\": \"6\", \"FullSearchTerm\": \"6 door\", \"Result\":true}, {\"SearchTerm\": \"6\", \"FullSearchTerm\": \"6 doors\", \"Result\":true}]",
          "FacetCurrencyRanges": "price,monthlyPrice",
          "FacetNonCurrencyRange": "mileage",
          "FacetMaxRangeToValue": 20000000,
          "FacetToOverrideDisplay": "engineSize,mileage,doors",
          "DefaultPageSize": 50,
          "DemoVehiclesURL": "https://s2storagedev.blob.core.windows.net/assets/test-data/vehicles.json?sv=2021-10-04&st=2023-04-03T20%3A59%3A51Z&se=2030-05-04T20%3A59%3A00Z&sr=c&sp=rl&sig=f1k11fTLD1womukuaGGFlA%2B79Xph6CLCrj5B403ZlMo%3D",
          "DemoVehiclesIndexSchemaURL": "https://s2storagedev.blob.core.windows.net/assets/test-data/s2-demo-vehicles.json?sv=2021-10-04&st=2023-04-03T20%3A59%3A51Z&se=2030-05-04T20%3A59%3A00Z&sr=c&sp=rl&sig=f1k11fTLD1womukuaGGFlA%2B79Xph6CLCrj5B403ZlMo%3D"
        },
        "FacetSettings": {
          "Make": "make, count:9999",
          "Model": "model, count:9999",
          "Variant": "variant, count:9999",
          "Location": "location, count:9999",
          "Price": "price, values:5001|10001|20001|30001|40001|50001|60001|70001|80001|90001|100001|150001|200001|500001|1000001",
          "MonthlyPrice": "monthlyPrice, values:201|401|601|801|1001|1501|2001",
          "Mileage": "mileage, values:1000|5000|10000|20000|30000|50000|75000|100000",
          "FuelType": "fuelType, count:9999",
          "Transmission": "transmission, count:9999",
          "Doors": "doors, count:9999",
          "EngineSize": "engineSize, count:9999",
          "BodyStyle": "bodyStyle, count:9999",
          "Colour": "colour, count:9999",
          "Year": "year, count:9999"
        },
        "ClientConfigurationSettings": {
          "ClientConfigurationEndpoint": "http://adminapi-api-service",
          "HeaderAPISubscriptionName": "Ocp-Apim-Subscription-Key",
          "APISubscriptionKey": "REDUNDANT"          
        },
        "MemoryCacheSettings": {
          "SearchCacheSlidingExpirySeconds": 1,
          "ConfigCacheSlidingExpirySeconds": 1,
          "DefaultFacetsCacheExpiryInSeconds": 60,
          "GenericSynonymsCacheExpiryInSeconds": 86400
        },
        "RedisCacheSettings": {
          "RedisConnectionString": "redis,ssl=false,password=a-very-complex-password-here,abortConnect=false,connectTimeout=15000,responseTimeout=5000",
          "DefaultCacheExpiryInSeconds": 3600
        },
        "AdminSettings": {
          "AdminEndpoint": "http://adminapi-api-service/"
        }
      }
    }
