apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: gitlab-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdHJ5LmdpdGxhYi5jb20iOnsidXNlcm5hbWUiOiJkcC1kZXYwIiwicGFzc3dvcmQiOiJBcWhzS3dTdzNZXzQ2ZVk2SHMyMyIsImF1dGgiOiJaSEF0WkdWMk1EcEJjV2h6UzNkVGR6TlpYelEyWlZrMlNITXlNdz09In19fQ==