apiVersion: v1
kind: Service
metadata:
  name: customerresource-api-service
  labels:
    app: s2customerresourceapi
spec:
  type: ClusterIP
  selector:
    app: s2customerresourceapi
  ports:
    - port: 80
      targetPort: 80
