apiVersion: v1
kind: Service
metadata:
  name: $env:SERVICENAME-service
  labels:
    app: $env:SERVICENAME
spec:
  selector:
    app: $env:SERVICENAME
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
