// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.CustomerResourceApi.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Customer
    {
        /// <summary>
        /// Initializes a new instance of the Customer class.
        /// </summary>
        public Customer()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Customer class.
        /// </summary>
        public Customer(System.Guid? customerId = default(System.Guid?), string businessName = default(string), string logoURL = default(string), string primaryThemeColour = default(string), string secondaryThemeColour = default(string))
        {
            CustomerId = customerId;
            BusinessName = businessName;
            LogoURL = logoURL;
            PrimaryThemeColour = primaryThemeColour;
            SecondaryThemeColour = secondaryThemeColour;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerId")]
        public System.Guid? CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "businessName")]
        public string BusinessName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "logoURL")]
        public string LogoURL { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "primaryThemeColour")]
        public string PrimaryThemeColour { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "secondaryThemeColour")]
        public string SecondaryThemeColour { get; set; }

    }
}
