// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.CustomerResourceApi.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NotificationPagedResults
    {
        /// <summary>
        /// Initializes a new instance of the NotificationPagedResults class.
        /// </summary>
        public NotificationPagedResults()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NotificationPagedResults class.
        /// </summary>
        public NotificationPagedResults(IList<Notification> results = default(IList<Notification>), int? totalCount = default(int?))
        {
            Results = results;
            TotalCount = totalCount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "results")]
        public IList<Notification> Results { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalCount")]
        public int? TotalCount { get; set; }

    }
}
