// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.CustomerResourceApi.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NotificationRule
    {
        /// <summary>
        /// Initializes a new instance of the NotificationRule class.
        /// </summary>
        public NotificationRule()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NotificationRule class.
        /// </summary>
        public NotificationRule(int? notificationRuleId = default(int?), int? transmitType = default(int?), string recipients = default(string), IList<string> recipientsList = default(IList<string>), int? triggerType = default(int?))
        {
            NotificationRuleId = notificationRuleId;
            TransmitType = transmitType;
            Recipients = recipients;
            RecipientsList = recipientsList;
            TriggerType = triggerType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "notificationRuleId")]
        public int? NotificationRuleId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transmitType")]
        public int? TransmitType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recipients")]
        public string Recipients { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recipientsList")]
        public IList<string> RecipientsList { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "triggerType")]
        public int? TriggerType { get; set; }

    }
}
