// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.CustomerResourceApi.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class QueryKey
    {
        /// <summary>
        /// Initializes a new instance of the QueryKey class.
        /// </summary>
        public QueryKey()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the QueryKey class.
        /// </summary>
        public QueryKey(string name = default(string), System.Guid? apiKey = default(System.Guid?))
        {
            Name = name;
            ApiKey = apiKey;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "apiKey")]
        public System.Guid? ApiKey { get; set; }

    }
}
