// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace S2Search.CustomerResourceApi.Client.AutoRest.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SearchInstanceRequest
    {
        /// <summary>
        /// Initializes a new instance of the SearchInstanceRequest class.
        /// </summary>
        public SearchInstanceRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SearchInstanceRequest class.
        /// </summary>
        public SearchInstanceRequest(string location = default(string), string pricingTier = default(string), bool? isShared = default(bool?))
        {
            Location = location;
            PricingTier = pricingTier;
            IsShared = isShared;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public string Location { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pricingTier")]
        public string PricingTier { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isShared")]
        public bool? IsShared { get; set; }

    }
}
