--THESE ARE EXAMPLE PASSWORDS TO CREATE A REFERENCE TO A LOGIN IN THE PROJECT
CREATE LOGIN [CustomerResourceApi] WITH PASSWORD = '$K@/NYP_G9E+]vu[';
GO
CREATE LOGIN [FeedServicesFunc] WITH PASSWORD = 'n2pf-x$vxmY4D5Wu';
GO
CREATE LOGIN [ProvisioningServicesFunc] WITH PASSWORD = 'T=]=n4*p89%_kB#d';
GO
CREATE LOGIN [SFTPGoServicesFunc] WITH PASSWORD = 'M>q^*9)aJahMDSu$';
GO
CREATE LOGIN [ClientConfigurationApi] WITH PASSWORD = 'ZLg6X67uFq3q';
GO
CREATE LOGIN [SearchInsightsFunc] WITH PASSWORD = '$YSac}yeKJjf4C=4';
GO