name: Build S2Search.CacheManager

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore APIs/S2Search.CacheManager/S2Search.CacheManager.csproj

      - name: Build
        run: dotnet build APIs/S2Search.CacheManager/S2Search.CacheManager.csproj --configuration Release --no-restore

      - name: Build Docker image
        run: docker build -t s2search-cachemanager:latest .
        working-directory: APIs/S2Search.CacheManager/CacheManager
