name: Build S2Search.Backend

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore APIs/S2Search.Backend/S2Search.Backend.csproj

      - name: Build
        run: dotnet build APIs/S2Search.Backend/S2Search.Backend.csproj --configuration Release --no-restore

      - name: Build Docker image
        run: docker build -t s2search-backend:latest .
        working-directory: APIs/S2Search.Backend

      - name: Set image tag from commit SHA
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Docker image for GHCR
        run: |
          docker tag s2search-backend:latest ghcr.io/${{ github.repository_owner }}/s2search-backend:latest
          docker tag s2search-backend:latest ghcr.io/${{ github.repository_owner }}/s2search-backend:${{ env.IMAGE_TAG }}

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/s2search-backend:latest
          docker push ghcr.io/${{ github.repository_owner }}/s2search-backend:${{ env.IMAGE_TAG }}
