name: Build S2Search.CacheManager

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      WORKDIR: CacheManager/S2Search.CacheManager
      PROJECT: CacheManager/S2Search.CacheManager/S2Search.CacheManager.csproj
      IMAGE_NAME: s2search-cachemanager

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT }}

      - name: Build
        run: dotnet build ${{ env.PROJECT }} --configuration Release --no-restore

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .
        working-directory: ${{ env.WORKDIR }}/CacheManager
