apiVersion: v1
kind: Service
metadata:
  name: sftpgo-service
  labels:
    app: sftpgo
spec:
  type: LoadBalancer
  selector:
    app: sftpgo
  ports:
    - name: http
      port: 2021
      targetPort: 8080
      protocol: TCP
    - name: sftp
      port: 2022
      targetPort: 2022
      protocol: TCP
